In [1]:
import numpy as np
import argparse
import imutils
import time 
import cv2
import os

In [43]:
start = time.time()
set_width = int(600)
normalize_image = 1/255.0
resize_image_shape = (1024, 512)
sample_img = cv2.imread('images/example_02.jpg')
sample_img = imutils.resize(sample_img, width=set_width)
blob_img = cv2.dnn.blobFromImage(sample_img, normalize_image, resize_image_shape, 0, swapRB=True, crop=False)

In [40]:
blob_img

array([[[[0.08627451, 0.09019608, 0.09411766, ..., 0.36078432,
          0.2901961 , 0.24705884],
         [0.09411766, 0.09803922, 0.10196079, ..., 0.37254903,
          0.32941177, 0.30588236],
         [0.10588236, 0.10980393, 0.1137255 , ..., 0.38823533,
          0.3921569 , 0.3921569 ],
         ...,
         [0.15686275, 0.15686275, 0.15686275, ..., 0.10588236,
          0.10588236, 0.10588236],
         [0.15686275, 0.15686275, 0.15686275, ..., 0.10980393,
          0.10980393, 0.10980393],
         [0.16078432, 0.16078432, 0.16078432, ..., 0.1137255 ,
          0.1137255 , 0.1137255 ]],

        [[0.10588236, 0.10980393, 0.1137255 , ..., 0.39607847,
          0.3254902 , 0.2784314 ],
         [0.11764707, 0.11764707, 0.12156864, ..., 0.4039216 ,
          0.3647059 , 0.3372549 ],
         [0.13333334, 0.13333334, 0.13725491, ..., 0.42352945,
          0.42352945, 0.42352945],
         ...,
         [0.18431373, 0.18431373, 0.18431373, ..., 0.13333334,
          0.13333334, 0.1

In [8]:
cv_enet_model = cv2.dnn.readNet('enet-cityscapes/enet-model.net')

In [9]:
cv_enet_model.setInput(blob_img)
cv_enet_model_output = cv_enet_model.forward()

In [23]:
cv_enet_model_output

array([[[[ 17.1363    ,  16.169312  ,  15.809857  , ...,  14.722057  ,
           18.384853  ,  17.529884  ],
         [ 14.830452  ,  13.804759  ,  14.445477  , ...,  13.353924  ,
           15.604312  ,  14.68977   ],
         [ 14.334621  ,  13.701331  ,  12.966048  , ...,  10.341312  ,
           15.920379  ,  15.238231  ],
         ...,
         [ 11.649584  ,  11.142058  ,   9.087632  , ...,   7.5810723 ,
           12.768024  ,  12.270065  ],
         [ 15.774449  ,  15.254591  ,  14.566139  , ...,  12.504254  ,
           16.352144  ,  15.88004   ],
         [ 14.537771  ,  14.002248  ,  13.6159725 , ...,  11.7295265 ,
           15.450281  ,  14.963059  ]],

        [[ -0.1977467 ,  -0.04956543,  -3.7981994 , ...,  -4.1091566 ,
           -1.9681611 ,  -1.8183802 ],
         [ -2.4890144 ,  -2.3874354 ,  -6.114351  , ...,  -6.4821067 ,
           -4.392799  ,  -4.232411  ],
         [ -0.95446354,  -0.90588194,  -4.736053  , ...,  -6.604812  ,
           -4.0999784 ,  -4.13230

In [10]:
label_values = open('enet-cityscapes/enet-classes.txt').read().strip().split("\n")

In [12]:
classes_num, h, w = cv_enet_model_output.shape[1:4]

In [13]:
class_map = np.argmax(cv_enet_model_output[0], axis=0)

In [24]:
class_map

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
import os
if os.path.isfile('enet-cityscapes/enet-colors.txt'):
    cv_enet_shape_img_colors = open('enet-cityscapes/enet-colors.txt').read().strip().split("\n")
    cv_enet_shape_img_colors = [np.array(c.split(",")).astype("int") for c in cv_enet_shape_img_colors]
    cv_enet_shape_img_colors = np.array(cv_enet_shape_img_colors)
else:
    np.random.seed(42)
    cv_enet_shape_img_colors = np.random.ranint(0, 255, size=(len(label_values) -1,3),dtype="unit8")
    cv_enet_shape_img_colors = np.vstack([[0,0,0], cv_enet_shape_img_colors]).astype("unit8")

In [25]:
mask_class_map = cv_enet_shape_img_colors[class_map]

In [26]:
mask_class_map = cv2.resize(mask_class_map, (sample_img.shape[1], sample_img.shape[0]), interpolation=cv2.INTER_NEAREST)
class_map = cv2.resize(class_map, (sample_img.shape[1], sample_img.shape[0]), interpolation=cv2.INTER_NEAREST)

In [27]:
mask_class_map

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [28]:
class_map

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [30]:
cv_enet_model_output = ((0.4*sample_img)+(0.6*mask_class_map))

In [31]:
cv_enet_model_output

array([[[ 8. , 10.8,  8.8],
        [ 8.8, 11.6,  9.6],
        [ 9.6, 12.4, 10.4],
        ...,
        [34. , 45.6, 41.6],
        [28.4, 40.8, 37.2],
        [16. , 28.4, 25.2]],

       [[10.4, 13.6, 10.8],
        [10.8, 14. , 11.6],
        [11.6, 14.8, 12. ],
        ...,
        [34.8, 46.8, 42.4],
        [30.8, 43.2, 39.6],
        [31.6, 44. , 40.8]],

       [[13.2, 16.8, 13.2],
        [12.4, 16. , 12.4],
        [12.8, 16.4, 12.8],
        ...,
        [35.2, 47.2, 42.8],
        [34.8, 47.2, 43.6],
        [34.8, 47.2, 44. ]],

       ...,

       [[15.6, 18.8, 16. ],
        [15.6, 18.8, 16. ],
        [15.6, 18.8, 16. ],
        ...,
        [11.6, 14.4, 11.6],
        [11.2, 14. , 11.2],
        [11.2, 14. , 11.2]],

       [[15.6, 18.8, 16. ],
        [15.6, 18.8, 16. ],
        [15.6, 18.8, 16. ],
        ...,
        [11.2, 14. , 11.2],
        [10.8, 13.6, 10.8],
        [10.8, 13.6, 10.8]],

       [[16. , 19.2, 16.4],
        [16. , 19.2, 16.4],
        [16. , 1

In [32]:
my_legend = np.zeros(((len(label_values)*25)+25,300,3))

In [46]:
for (i, (class_name, img_color)) in enumerate(zip(label_values, cv_enet_shape_img_colors)):
    # draw the class name + color on the legend
    color_info = [int(color) for color in img_color]
    cv2.putText(my_legend, class_name, (5, (i * 25) + 17),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
    cv2.rectangle(my_legend, (100, (i * 25)), (300, (i * 25) + 25),
                  tuple(color_info), -1)
cv2.imshow("My_Legend", my_legend)
cv2.imshow("Img_Input", sample_img)
cv2.imshow("CV_Model_Output", cv_enet_model_output)
cv2.waitKey(0)
cv2.destroyAllWindows()

end = time.time()
